// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq7aDJAfCKXy-ARFmcgmaXT8T66VX-cts',
    appId: '1:265150846702:web:1ef1b1e192c7e8ce5f45ff',
    messagingSenderId: '265150846702',
    projectId: 'coast-terminal-b873c',
    authDomain: 'coast-terminal-b873c.firebaseapp.com',
    databaseURL: 'https://coast-terminal-b873c-default-rtdb.firebaseio.com',
    storageBucket: 'coast-terminal-b873c.appspot.com',
    measurementId: 'G-XJFYBJ6Z8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMhE8EdWgDOyz0syGxar2uLGsEMEavp84',
    appId: '1:265150846702:android:6a17eb55833441cb5f45ff',
    messagingSenderId: '265150846702',
    projectId: 'coast-terminal-b873c',
    databaseURL: 'https://coast-terminal-b873c-default-rtdb.firebaseio.com',
    storageBucket: 'coast-terminal-b873c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Z16iVobTuoG-XvixU6fICPH67dzNgY4',
    appId: '1:265150846702:ios:54cca9ec9471e0a35f45ff',
    messagingSenderId: '265150846702',
    projectId: 'coast-terminal-b873c',
    databaseURL: 'https://coast-terminal-b873c-default-rtdb.firebaseio.com',
    storageBucket: 'coast-terminal-b873c.appspot.com',
    iosClientId: '265150846702-5o37i5dshnciis8aft5sjodijurvss3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.coastTerminal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Z16iVobTuoG-XvixU6fICPH67dzNgY4',
    appId: '1:265150846702:ios:54cca9ec9471e0a35f45ff',
    messagingSenderId: '265150846702',
    projectId: 'coast-terminal-b873c',
    databaseURL: 'https://coast-terminal-b873c-default-rtdb.firebaseio.com',
    storageBucket: 'coast-terminal-b873c.appspot.com',
    iosClientId: '265150846702-5o37i5dshnciis8aft5sjodijurvss3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.coastTerminal',
  );
}
